# Generated by Django 5.1.4 on 2024-12-23 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='conetent',
            new_name='content',
        ),
    ]
